from generated.MotorAutoGenerated import MotorAutoGenerated
from CurrentControl import CurrentControl
from Rotor import Rotor
class Motor(MotorAutoGenerated):
	def __init__(self,nr,odrive):
		self.nr = nr
		self.odrive = odrive
		self.current_control = CurrentControl(self) 
		self.rotor = Rotor(self)
