import sys
import serial
from generated.ODriveAutoGenerated import ODriveAutoGenerated

from Motor import Motor

DEBUG = True

class ODrive(ODriveAutoGenerated):
	def __init__(self,tty):	
		self._serial = serial.Serial(tty)  # open serial port
		self.motors = [
			Motor(0,self),
			Motor(1,self),
		]

	def print_monitoring(self,limit):
		print self.command("o %s" % limit)

	def command(self, commandstr):
		if DEBUG:
			print "sending '%s'" % commandstr
		self._serial.write(commandstr)	
		
		r = self._serial.readline()
		if DEBUG:
			print "received '%s'" % r 
		return r


if __name__ == "__main__":
	
	odrive = ODrive(sys.argv[1])	
	from IPython import embed
	embed()
