Dev_Env = tup.getconfig("DEVELOPMENT_IDE")


tup.include('build.lua')
boarddir = "" -- No Board Loaded Yet
boardversion = tup.getconfig("BOARD_VERSION")
tup.include("Board/HAL_Generics/Generics.lua") -- Generic HAL functions for simplifying HAL dev

--> Add Other HAL Tests Here
tup.include("Board/v3/HAL_V3.x.lua")


-->


if boarddir == "" then
    error("Unknown Board. Check Your Config. "..boardversion)
end
buildsuffix = boardversion

-- USB I/O settings
if tup.getconfig("USB_PROTOCOL") == "native" or tup.getconfig("USB_PROTOCOL") == "" then
    FLAGS += "-DUSB_PROTOCOL_NATIVE"
elseif tup.getconfig("USB_PROTOCOL") == "native-stream" then
    FLAGS += "-DUSB_PROTOCOL_NATIVE_STREAM_BASED"
elseif tup.getconfig("USB_PROTOCOL") == "stdout" then
    FLAGS += "-DUSB_PROTOCOL_STDOUT"
elseif tup.getconfig("USB_PROTOCOL") == "none" then
    FLAGS += "-DUSB_PROTOCOL_NONE"
else
    error("unknown USB protocol")
end

-- UART I/O settings
if tup.getconfig("UART_PROTOCOL") == "native" then
    FLAGS += "-DUART_PROTOCOL_NATIVE"
elseif tup.getconfig("UART_PROTOCOL") == "ascii" or tup.getconfig("UART_PROTOCOL") == "" then
    FLAGS += "-DUART_PROTOCOL_ASCII"
elseif tup.getconfig("UART_PROTOCOL") == "stdout" then
    FLAGS += "-DUART_PROTOCOL_STDOUT"
elseif tup.getconfig("UART_PROTOCOL") == "none" then
    FLAGS += "-DUART_PROTOCOL_NONE"
else
    error("unknown UART protocol "..tup.getconfig("UART_PROTOCOL"))
end

-- GPIO settings
if tup.getconfig("STEP_DIR") == "y" then
    if tup.getconfig("UART_PROTOCOL") == "none" then
        FLAGS += "-DUSE_GPIO_MODE_STEP_DIR"
    else
        error("Step/dir mode conflicts with UART. Set CONFIG_UART_PROTOCOL to none.")
    end
end

-- Compiler settings
if tup.getconfig("STRICT") == "true" then
    FLAGS += '-Werror'
end


-- C-specific flags
FLAGS += '-D__weak="__attribute__((weak))"'
FLAGS += '-D__packed="__attribute__((__packed__))"'
FLAGS += '-mthumb'
FLAGS += { '-Wall', '-Wdouble-promotion', '-Wfloat-conversion', '-fdata-sections', '-ffunction-sections'}

-- debug build
FLAGS += '-g -gdwarf-2'


-- linker flags
LDFLAGS += '-mthumb -specs=nosys.specs -specs=nano.specs -u _printf_float -u _scanf_float -Wl,--cref -Wl,--gc-sections'
LDFLAGS += '-Wl,--undefined=uxTopUsedPriority'


-- common flags for ASM, C and C++
OPT += '-Og'
-- OPT += '-O0'
OPT += '-ffast-math -fno-finite-math-only'
tup.append_table(FLAGS, OPT)
tup.append_table(LDFLAGS, OPT)

toolchain = GCCToolchain('arm-none-eabi-', 'build', FLAGS, LDFLAGS)


-- Load list of source files Makefile that was autogenerated by CubeMX
vars = parse_makefile_vars(boarddir..'/Makefile')
all_stm_sources = (vars['C_SOURCES'] or '')..' '..(vars['CPP_SOURCES'] or '')..' '..(vars['ASM_SOURCES'] or '')
for src in string.gmatch(all_stm_sources, "%S+") do
    stm_sources += boarddir..'/'..src
end
for src in string.gmatch(vars['C_INCLUDES'] or '', "%S+") do
    stm_includes += boarddir..'/'..string.sub(src, 3, -1) -- remove "-I" from each include path
end

-- TODO: cleaner separation of the platform code and the rest
stm_includes += '.'
stm_includes += 'Drivers/DRV8301'
stm_sources += boarddir..'/Src/syscalls.c'
build{
    name='stm_platform',
    type='objects',
    toolchains={toolchain},
    packages={},
    sources=stm_sources,
    includes=stm_includes
}

tup.frule{
    command='python ../tools/odrive/version.py --output %o',
    outputs={'build/version.h'}
}

build{
    name='ODriveFirmware',
    toolchains={toolchain},
    --toolchains={LLVMToolchain('x86_64', {'-Ofast'}, {'-flto'})},
    packages={'stm_platform'},
    sources={
        'Drivers/DRV8301/drv8301.c',
        'MotorControl/utils.c',
        'MotorControl/arm_sin_f32.c',
        'MotorControl/arm_cos_f32.c',
        'MotorControl/low_level.cpp',
        'MotorControl/nvm.c',
        'MotorControl/axis.cpp',
        'MotorControl/motor.cpp',
        'MotorControl/encoder.cpp',
        'MotorControl/controller.cpp',
        'MotorControl/sensorless_estimator.cpp',
        'MotorControl/trapTraj.cpp',
        'MotorControl/main.cpp',
        'communication/communication.cpp',
        'communication/ascii_protocol.cpp',
        'communication/interface_uart.cpp',
        'communication/interface_usb.cpp',
        'communication/interface_can.cpp',
        'communication/interface_i2c.cpp',
        'fibre/cpp/protocol.cpp',
        'FreeRTOS-openocd.c'
    },
    includes={
        'Drivers/DRV8301',
        'MotorControl',
        'fibre/cpp/include',
        '.'
    }
}

if Dev_Env == "CLION" then
    --> Rule for allowing code completion with CLion.
    tup.frule{
        inputs=b,
        command="python ../tools/builders/GenerateCMakeLists.py --SRC $(all_source) $(stm_sources) --INC $(all_inc) $(stm_includes) --FLAG $(FLAGS) $(LDFLAGS) ",
        outputs={"CMakeListsPrivate.txt"}
    }
end