name: Build and publish HTML documentation website

on:
  push:
    branches: [ master ]
    paths: ['docs/**', '.github/**']

jobs:
  make-html:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-sphinx-sphinx-tabs-sphinx-design-sphinx_copybutton-sphinx_panels-sphinx_rtd_theme
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install Python dependencies
      run: pip install sphinx sphinx-tabs sphinx-design sphinx_copybutton sphinx_panels sphinx_rtd_theme
    
    - name: Build HTML docs
      run: |
        cd docs
        make html

    - name: Upload docs
      uses: ./.github/actions/upload-release
      with:
        release_type: docs
        src_dir: docs/_build/html
        do_access_key: ${{ secrets.DIGITALOCEAN_ACCESS_KEY }}
        do_secret_key: ${{ secrets.DIGITALOCEAN_SECRET_KEY }}
        odrive_api_key: ${{ secrets.ODRIVE_API_KEY }}
        variant: public
